name: KitsX
description: A modern kits plugin for the Crystal PvP server.
main: dev.darkxx.kitsx.KitsX
version: '1.0.3'
api-version: '1.21'
website: https://xyris.fun/
authors:
  - Darkxx
  - XyrisPlugins
  - NotZorba (forked)
softdepend:
  - WorldGuard
  - Skript
# dependencies:
#  server:
#    WorldGuard:
#      load: BEFORE
#      required: false
#    Skript:
#      load: BEFORE
#      required: false

permissions:
  kitsx.admin:
    default: op
  kitsx.autokit:
    default: op
  kitsx.cooldown.bypass:
    default: op
    description: Allows bypassing the kit load cooldown.